### ISSUE TITLE
windows/mc_start.bat, Failed to locate library: lwjgl.dll

### ISSUE THREAD

**Issue by BoQsc** [iiiypuk/minecraft-launcher#7]
I tried to use your minecraft launcher script: https://github.com/iiiypuk/minecraft-launcher/blob/master/windows/mc_start.bat

But it seems to not launch the minecraft. I used your launch code on both: **1.14.1** and **1.14.2**
And neither did launch. **And didn't print any error.**

Since there were absolutely no errors. I changed your script little bit:

* I changed "javaw.exe" to "java.exe".
* I launched **mc_start.bat**

**This is what I saw:** 
```
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[11:11:43] [Client thread/INFO]: Setting user: Steve
[11:11:47] [Client thread/INFO]: LWJGL Version: 3.2.1 build 12
[11:19:06] [Client thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
        a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
        b) Add the JAR that contains the shared library to the classpath.
[11:19:06] [Client thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[11:19:06] [Client thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 19.6.24 11.19
Description: Initializing game

java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
        at org.lwjgl.system.Library.loadSystem(Library.java:147)
        at org.lwjgl.system.Library.loadSystem(Library.java:67)
        at org.lwjgl.system.Library.<clinit>(Library.java:50)
        at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
        at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:61)
        at cud.a(SourceFile:106)
        at com.mojang.blaze3d.platform.GLX.initGlfw(SourceFile:191)
        at cvk.au(SourceFile:459)
        at cvk.b(SourceFile:395)
        at net.minecraft.client.main.Main.main(SourceFile:154)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
        at org.lwjgl.system.Library.loadSystem(Library.java:147)
        at org.lwjgl.system.Library.loadSystem(Library.java:67)
        at org.lwjgl.system.Library.<clinit>(Library.java:50)
        at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
        at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:61)
        at cud.a(SourceFile:106)
        at com.mojang.blaze3d.platform.GLX.initGlfw(SourceFile:191)
        at cvk.au(SourceFile:459)

-- Initialization --
Details:
Stacktrace:
        at cvk.b(SourceFile:395)
        at net.minecraft.client.main.Main.main(SourceFile:154)

-- System Details --
Details:
        Minecraft Version: 1.14.1
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 1.8.0_211, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 138801616 bytes (132 MB) / 362459136 bytes (345 MB) up to 1060372480 bytes (1011 MB)
        JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
        Launched Version: 1.14.1
        LWJGL: 3.2.1 build 12
        OpenGL: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.system.Library
        GL Caps:
        Using VBOs: Yes
        Is Modded: Probably not. Jar signature remains and client brand is untouched.
        Type: Client (map_client.txt)
        Resource Packs:
        Current Language: ~~ERROR~~ NullPointerException: null
        CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Juozas\AppData\Roaming\.minecraft\profile\crash-reports\crash-2019-06-24_11.19.07-client.txt
Press any key to continue . . .
```

**Comment by iiiypuk** [comment]
Checked on another computer. It starts.
![mc_check](https://user-images.githubusercontent.com/1431900/60391122-3562b280-9af0-11e9-8ad8-4e1f9336cc1d.png)
